[project]
name="pepper-growth-ml"
dependencies=["matplotlib","pandas","jupyter"]
authors=[{name="Robert Streetman", email="robert.streetman@mailfence.com"}]
description="Python library to predict pepper growth based on environmental factors"
readme="README.md"
license="GPL-3.0-or-later"
license-files=["LICENSE.txt"]

[build-system]
requires=["hatchling"]
build-backend="hatchling.build"